Controller:
  ros__parameters:
    time_step: 0.1

    speed:
      maximum: 5.0

      minimum: 2.0

    gains:
      proportional: 2.0

      integral: 0.0

      differential: 0.0

      lookAhead: 0.3

    constants:
      speed: 21.0

      lookahead: 1.1

    drive: "/ackr"

    state: "/carmaker/Odometry"

    path: "/path"
